os: linux
language: generic
matrix:
  include:
    - name: TRUSTY / LATEST
      dist: trusty
      env:
        - VERSION="latest"
    - name: XENIAL / LATEST
      dist: xenial
      env:
        - VERSION="latest"
    - name: XENIAL / 1.9.34
      dist: xenial
      env:
        - VERSION="1.9.34"
    - name: XENIAL / 1.9.32
      dist: xenial
      env:
        - VERSION="1.9.32"
    - name: XENIAL / 1.9.30
      dist: xenial
      env:
        - VERSION="1.9.30"
    - name: XENIAL / 1.9.28
      dist: xenial
      env:
        - VERSION="1.9.28"
    - name: XENIAL / 1.9.26
      dist: xenial
      env:
        - VERSION="1.9.26"
    - name: XENIAL / 1.9.24
      dist: xenial
      env:
        - VERSION="1.9.24"
    - name: XENIAL / 1.9.22
      dist: xenial
      env:
        - VERSION="1.9.22"
    - name: XENIAL / 1.9.20
      dist: xenial
      env:
        - VERSION="1.9.20"
notifications:
  email:
    recipients:
      - make@roboxes.org
    on_success: never
    on_failure: always
script:
  - touch failed.log ; touch retry.log ; touch passed.log ; function travis_result() { echo &> /dev/null ; }
  - (curl --silent --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" --output /dev/null --url https://lavabit.com --output /dev/null --url https://roboxes.org) & CURL_PID=$! ; disown
  - (for ((i = 0; i < 256; ++i)); do sleep 20 ; printf "%s (%s )\n" "`date`" "`uptime`" ; done) & LOOP_PID=$! ; disown
  - (travis_retry docker pull roboxes/centos6:$VERSION &> /dev/null || (echo "roboxes-centos6-version download failed" | tee -a failed.log) && echo "roboxes-centos6-version download complete") &
  - (travis_retry docker pull roboxes/centos7:$VERSION &> /dev/null || (echo "roboxes-centos7-version download failed" | tee -a failed.log) && echo "roboxes-centos7-version download complete") &
  - (travis_retry docker pull roboxes/centos8:$VERSION &> /dev/null || (echo "roboxes-centos8-version download failed" | tee -a failed.log) && echo "roboxes-centos8-version download complete") &
  - (travis_retry docker pull roboxes/oracle7:$VERSION &> /dev/null || (echo "roboxes-oracle7-version download failed" | tee -a failed.log) && echo "roboxes-oracle7-version download complete") &
  - (travis_retry docker pull roboxes/oracle8:$VERSION &> /dev/null || (echo "roboxes-oracle8-version download failed" | tee -a failed.log) && echo "roboxes-oracle8-version download complete") &
  - wait
  - (travis_retry docker pull roboxes/rhel6:$VERSION &> /dev/null || (echo "roboxes-rhel6-version download failed" | tee -a failed.log) && echo "roboxes-rhel6-version download complete") &
  - (travis_retry docker pull roboxes/rhel7:$VERSION &> /dev/null || (echo "roboxes-rhel7-version download failed" | tee -a failed.log) && echo "roboxes-rhel7-version download complete") &
  - (travis_retry docker pull roboxes/rhel8:$VERSION &> /dev/null || (echo "roboxes-rhel8-version download failed" | tee -a failed.log) && echo "roboxes-rhel8-version download complete") &
  - (travis_retry docker pull lavabit/magma:$VERSION &> /dev/null || (echo "magma-version download failed" | tee -a failed.log) && echo "magma-version download complete") &
  - (travis_retry docker pull lavabit/magma-centos:$VERSION &> /dev/null || (echo "magma-centos-version download failed" | tee -a failed.log) && echo "magma-centos-version download complete") &
  - (travis_retry docker pull lavabit/magma-centos6:$VERSION &> /dev/null || (echo "magma-centos6-version download failed" | tee -a failed.log) && echo "magma-centos6-version download complete") &
  - (travis_retry docker pull lavabit/magma-centos7:$VERSION &> /dev/null || (echo "magma-centos7-version download failed" | tee -a failed.log) && echo "magma-centos7-version download complete") &
  - wait
  - (travis_retry docker run roboxes/centos6:$VERSION curl --silent --show-error --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" https://lavabit.com > /dev/null || (echo "roboxes-centos6-version run failed" | tee -a failed.log) && echo "roboxes-centos6-version run complete") &
  - (travis_retry docker run roboxes/centos7:$VERSION curl --silent --show-error --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" https://lavabit.com > /dev/null || (echo "roboxes-centos7-version run failed" | tee -a failed.log) && echo "roboxes-centos7-version run complete") &
  - (travis_retry docker run roboxes/centos8:$VERSION curl --silent --show-error --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" https://lavabit.com > /dev/null || (echo "roboxes-centos8-version run failed" | tee -a failed.log) && echo "roboxes-centos8-version run complete") &
  - (travis_retry docker run roboxes/oracle7:$VERSION curl --silent --show-error --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" https://lavabit.com > /dev/null || (echo "roboxes-oracle7-version run failed" | tee -a failed.log) && echo "roboxes-oracle7-version run complete") &
  - (travis_retry docker run roboxes/oracle8:$VERSION curl --silent --show-error --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" https://lavabit.com > /dev/null || (echo "roboxes-oracle8-version run failed" | tee -a failed.log) && echo "roboxes-oracle8-version run complete") &
  - wait
  - (travis_retry docker run roboxes/rhel6:$VERSION curl --silent --show-error --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" https://lavabit.com > /dev/null || (echo "roboxes-rhel6-version run failed" | tee -a failed.log) && echo "roboxes-rhel6-version run complete") &
  - (travis_retry docker run roboxes/rhel7:$VERSION curl --silent --show-error --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" https://lavabit.com > /dev/null || (echo "roboxes-rhel7-version run failed" | tee -a failed.log) && echo "roboxes-rhel7-version run complete") &
  - (travis_retry docker run roboxes/rhel8:$VERSION curl --silent --show-error --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" https://lavabit.com > /dev/null || (echo "roboxes-rhel8-version run failed" | tee -a failed.log) && echo "roboxes-rhel8-version run complete") &
  - (travis_retry docker run lavabit/magma:$VERSION curl --silent --show-error --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" https://lavabit.com > /dev/null || (echo "magma-version run failed" | tee -a failed.log) && echo "magma-version run complete") &
  - (travis_retry docker run lavabit/magma-centos:$VERSION curl --silent --show-error --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" https://lavabit.com > /dev/null || (echo "magma-centos-version run failed" | tee -a failed.log) && echo "magma-centos-version run complete") &
  - (travis_retry docker run lavabit/magma-centos6:$VERSION curl --silent --show-error --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" https://lavabit.com > /dev/null || (echo "magma-centos6-version run failed" | tee -a failed.log) && echo "magma-centos6-version run complete") &
  - (travis_retry docker run lavabit/magma-centos7:$VERSION curl --silent --show-error --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" https://lavabit.com > /dev/null || (echo "magma-centos7-version run failed" | tee -a failed.log) && echo "magma-centos7-version run complete") &
  - wait
  - ifconfig | grep --extended-regexp --color=none "encap:Ethernet  HWaddr|RX bytes|TX bytes" | head -n -1
  - export RESULT=`cat failed.log | wc -l`
  - cat failed.log | sort
  - echo "Version ${VERSION}"
  - echo "Total Failures ${RESULT}"
  - if [[ $RESULT != 0 ]]; then exit 1; fi
  - exit 0
