os: linux
language: c
dist: trusty
group: stable
compiler: gcc
env:
  - VERSION="1.8.50"
notifications:
  email:
    recipients:
      - make@roboxes.org
    on_success: never
    on_failure: never
script:
  - touch failure.log
  - (for ((i = 0; i < 60; ++i)); do date ; sleep 480; done) & looper=$! ; disown
  - (docker pull roboxes/centos6:$VERSION&> /dev/null || (echo "roboxes-centos6-version failed" | tee -a failure.log) && echo "roboxes-centos6-version complete") &
  - (docker pull roboxes/centos7:$VERSION&> /dev/null || (echo "roboxes-centos7-version failed" | tee -a failure.log) && echo "roboxes-centos7-version complete") &
  - (docker pull lavabit/magma:$VERSION&> /dev/null || (echo "magma-version failed" | tee -a failure.log) && echo "magma-version complete") &
  - (docker pull lavabit/magma-centos:$VERSION&> /dev/null || (echo "magma-centos-version failed" | tee -a failure.log) && echo "magma-centos-version complete") &
  - (docker pull lavabit/magma-centos6:$VERSION&> /dev/null || (echo "magma-centos6-version failed" | tee -a failure.log) && echo "magma-centos6-version complete") &
  - (docker pull lavabit/magma-centos7:$VERSION&> /dev/null || (echo "magma-centos7-version failed" | tee -a failure.log) && echo "magma-centos7-version complete") &
  - (docker pull roboxes/centos6:latest&> /dev/null || (echo "roboxes-centos6-latest failed" | tee -a failure.log) && echo "roboxes-centos6-latest complete") &
  - (docker pull roboxes/centos7:latest&> /dev/null || (echo "roboxes-centos7-latest failed" | tee -a failure.log) && echo "roboxes-centos7-latest complete") &
  - (docker pull lavabit/magma:latest&> /dev/null || (echo "magma-latest failed" | tee -a failure.log) && echo "magma-latest complete") &
  - (docker pull lavabit/magma-centos:latest&> /dev/null || (echo "magma-centos-latest failed" | tee -a failure.log) && echo "magma-centos-latest complete") &
  - (docker pull lavabit/magma-centos6:latest&> /dev/null || (echo "magma-centos6-latest failed" | tee -a failure.log) && echo "magma-centos6-latest complete") &
  - (docker pull lavabit/magma-centos7:latest&> /dev/null || (echo "magma-centos7-latest failed" | tee -a failure.log) && echo "magma-centos7-latest complete") &
  - wait
  - docker images
  - export RESULT=`cat failure.log | wc -l`
  - ifconfig eth0 | grep --extended-regexp --color=none "RX bytes|TX bytes"
  - cat failure.log | sort
  - echo "Version ${VERSION}"
  - echo "Total Failures ${RESULT}"
  - if [[ $RESULT != 0 ]]; then exit 1; fi
